//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrionCoreCableColor.DbConnection.CoreAdministrativoDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Control_MesContable
    {
        public int fiIDControlMesContable { get; set; }
        public int fiIDEmpresa { get; set; }
        public int fiAnio { get; set; }
        public int fiMes { get; set; }
        public bool fbMesCerrado { get; set; }
        public string fcComentario { get; set; }
        public System.DateTime fdFechaCreacion { get; set; }
        public System.DateTime fdFechaModificacion { get; set; }
        public string fcUsuarioCreador { get; set; }
        public string fcUsuarioModificador { get; set; }
        public bool fbActivo { get; set; }
    }
}
