//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrionCoreCableColor.DbConnection.CoreFinancieroDB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CoreFinancieroEntities2 : DbContext
    {
        public CoreFinancieroEntities2()
            : base("name=CoreFinancieroEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<sp_Facturacion_ConsultarFactura_Result> sp_Facturacion_ConsultarFactura(Nullable<int> piIDTransaccion, string pcFactura)
        {
            var piIDTransaccionParameter = piIDTransaccion.HasValue ?
                new ObjectParameter("piIDTransaccion", piIDTransaccion) :
                new ObjectParameter("piIDTransaccion", typeof(int));
    
            var pcFacturaParameter = pcFactura != null ?
                new ObjectParameter("pcFactura", pcFactura) :
                new ObjectParameter("pcFactura", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Facturacion_ConsultarFactura_Result>("sp_Facturacion_ConsultarFactura", piIDTransaccionParameter, pcFacturaParameter);
        }
    
        public virtual ObjectResult<sp_OperacionesBanco_CuentasdeBanco_Result> sp_OperacionesBanco_CuentasdeBanco(Nullable<int> piIDSesion, Nullable<short> piIDApp, Nullable<int> piIDUsuario, Nullable<int> piIDEmpresa)
        {
            var piIDSesionParameter = piIDSesion.HasValue ?
                new ObjectParameter("piIDSesion", piIDSesion) :
                new ObjectParameter("piIDSesion", typeof(int));
    
            var piIDAppParameter = piIDApp.HasValue ?
                new ObjectParameter("piIDApp", piIDApp) :
                new ObjectParameter("piIDApp", typeof(short));
    
            var piIDUsuarioParameter = piIDUsuario.HasValue ?
                new ObjectParameter("piIDUsuario", piIDUsuario) :
                new ObjectParameter("piIDUsuario", typeof(int));
    
            var piIDEmpresaParameter = piIDEmpresa.HasValue ?
                new ObjectParameter("piIDEmpresa", piIDEmpresa) :
                new ObjectParameter("piIDEmpresa", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_OperacionesBanco_CuentasdeBanco_Result>("sp_OperacionesBanco_CuentasdeBanco", piIDSesionParameter, piIDAppParameter, piIDUsuarioParameter, piIDEmpresaParameter);
        }
    
        public virtual ObjectResult<sp_OperacionesCaja_AplicarAbono_NovaNet_Result> sp_OperacionesCaja_AplicarAbono_NovaNet(Nullable<short> piIDApp, Nullable<int> piIDUsuario, string pcIP, string pcIdentidad, Nullable<decimal> pnValordelAbono, string pcIDPrestamo, string pcComentarioAdicional, string pcCuentaOrigenMonedaNacional, string pcReferencia, ObjectParameter piIDTransaccion, Nullable<System.DateTime> pdFechadeTransaccion, Nullable<int> piIDMovimientoPrimerPago, Nullable<int> piIDUsuarioSRC)
        {
            var piIDAppParameter = piIDApp.HasValue ?
                new ObjectParameter("piIDApp", piIDApp) :
                new ObjectParameter("piIDApp", typeof(short));
    
            var piIDUsuarioParameter = piIDUsuario.HasValue ?
                new ObjectParameter("piIDUsuario", piIDUsuario) :
                new ObjectParameter("piIDUsuario", typeof(int));
    
            var pcIPParameter = pcIP != null ?
                new ObjectParameter("pcIP", pcIP) :
                new ObjectParameter("pcIP", typeof(string));
    
            var pcIdentidadParameter = pcIdentidad != null ?
                new ObjectParameter("pcIdentidad", pcIdentidad) :
                new ObjectParameter("pcIdentidad", typeof(string));
    
            var pnValordelAbonoParameter = pnValordelAbono.HasValue ?
                new ObjectParameter("pnValordelAbono", pnValordelAbono) :
                new ObjectParameter("pnValordelAbono", typeof(decimal));
    
            var pcIDPrestamoParameter = pcIDPrestamo != null ?
                new ObjectParameter("pcIDPrestamo", pcIDPrestamo) :
                new ObjectParameter("pcIDPrestamo", typeof(string));
    
            var pcComentarioAdicionalParameter = pcComentarioAdicional != null ?
                new ObjectParameter("pcComentarioAdicional", pcComentarioAdicional) :
                new ObjectParameter("pcComentarioAdicional", typeof(string));
    
            var pcCuentaOrigenMonedaNacionalParameter = pcCuentaOrigenMonedaNacional != null ?
                new ObjectParameter("pcCuentaOrigenMonedaNacional", pcCuentaOrigenMonedaNacional) :
                new ObjectParameter("pcCuentaOrigenMonedaNacional", typeof(string));
    
            var pcReferenciaParameter = pcReferencia != null ?
                new ObjectParameter("pcReferencia", pcReferencia) :
                new ObjectParameter("pcReferencia", typeof(string));
    
            var pdFechadeTransaccionParameter = pdFechadeTransaccion.HasValue ?
                new ObjectParameter("pdFechadeTransaccion", pdFechadeTransaccion) :
                new ObjectParameter("pdFechadeTransaccion", typeof(System.DateTime));
    
            var piIDMovimientoPrimerPagoParameter = piIDMovimientoPrimerPago.HasValue ?
                new ObjectParameter("piIDMovimientoPrimerPago", piIDMovimientoPrimerPago) :
                new ObjectParameter("piIDMovimientoPrimerPago", typeof(int));
    
            var piIDUsuarioSRCParameter = piIDUsuarioSRC.HasValue ?
                new ObjectParameter("piIDUsuarioSRC", piIDUsuarioSRC) :
                new ObjectParameter("piIDUsuarioSRC", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_OperacionesCaja_AplicarAbono_NovaNet_Result>("sp_OperacionesCaja_AplicarAbono_NovaNet", piIDAppParameter, piIDUsuarioParameter, pcIPParameter, pcIdentidadParameter, pnValordelAbonoParameter, pcIDPrestamoParameter, pcComentarioAdicionalParameter, pcCuentaOrigenMonedaNacionalParameter, pcReferenciaParameter, piIDTransaccion, pdFechadeTransaccionParameter, piIDMovimientoPrimerPagoParameter, piIDUsuarioSRCParameter);
        }
    
        public virtual ObjectResult<sp_OperacionesCaja_UltimosMovimientos_Result> sp_OperacionesCaja_UltimosMovimientos(string pcIDPrestamo)
        {
            var pcIDPrestamoParameter = pcIDPrestamo != null ?
                new ObjectParameter("pcIDPrestamo", pcIDPrestamo) :
                new ObjectParameter("pcIDPrestamo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_OperacionesCaja_UltimosMovimientos_Result>("sp_OperacionesCaja_UltimosMovimientos", pcIDPrestamoParameter);
        }
    
        public virtual ObjectResult<sp_OperacionesCaja_ConsultarAbono_Result> sp_OperacionesCaja_ConsultarAbono(Nullable<int> piIDTransaccion, Nullable<int> piInformacionFactura)
        {
            var piIDTransaccionParameter = piIDTransaccion.HasValue ?
                new ObjectParameter("piIDTransaccion", piIDTransaccion) :
                new ObjectParameter("piIDTransaccion", typeof(int));
    
            var piInformacionFacturaParameter = piInformacionFactura.HasValue ?
                new ObjectParameter("piInformacionFactura", piInformacionFactura) :
                new ObjectParameter("piInformacionFactura", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_OperacionesCaja_ConsultarAbono_Result>("sp_OperacionesCaja_ConsultarAbono", piIDTransaccionParameter, piInformacionFacturaParameter);
        }
    
        public virtual ObjectResult<sp_Facturacion_ConsultarFactura_NovaNet_Result> sp_Facturacion_ConsultarFactura_NovaNet(Nullable<int> piIDTransaccion, string pcFactura)
        {
            var piIDTransaccionParameter = piIDTransaccion.HasValue ?
                new ObjectParameter("piIDTransaccion", piIDTransaccion) :
                new ObjectParameter("piIDTransaccion", typeof(int));
    
            var pcFacturaParameter = pcFactura != null ?
                new ObjectParameter("pcFactura", pcFactura) :
                new ObjectParameter("pcFactura", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Facturacion_ConsultarFactura_NovaNet_Result>("sp_Facturacion_ConsultarFactura_NovaNet", piIDTransaccionParameter, pcFacturaParameter);
        }
    
        public virtual ObjectResult<sp_Prestamo_PlandePago_ConsultarAvancePorPrestamo_Result> sp_Prestamo_PlandePago_ConsultarAvancePorPrestamo(string pcIDPrestamo)
        {
            var pcIDPrestamoParameter = pcIDPrestamo != null ?
                new ObjectParameter("pcIDPrestamo", pcIDPrestamo) :
                new ObjectParameter("pcIDPrestamo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Prestamo_PlandePago_ConsultarAvancePorPrestamo_Result>("sp_Prestamo_PlandePago_ConsultarAvancePorPrestamo", pcIDPrestamoParameter);
        }
    
        public virtual ObjectResult<sp_SRCClientesPlandePago_Result> sp_SRCClientesPlandePago(string pcIDCLiente, string pcIDPrestamo)
        {
            var pcIDCLienteParameter = pcIDCLiente != null ?
                new ObjectParameter("pcIDCLiente", pcIDCLiente) :
                new ObjectParameter("pcIDCLiente", typeof(string));
    
            var pcIDPrestamoParameter = pcIDPrestamo != null ?
                new ObjectParameter("pcIDPrestamo", pcIDPrestamo) :
                new ObjectParameter("pcIDPrestamo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_SRCClientesPlandePago_Result>("sp_SRCClientesPlandePago", pcIDCLienteParameter, pcIDPrestamoParameter);
        }
    
        public virtual int SP_SRCEstadoDeCuenta(string pcIDCLiente, string pcIDPrestamo)
        {
            var pcIDCLienteParameter = pcIDCLiente != null ?
                new ObjectParameter("pcIDCLiente", pcIDCLiente) :
                new ObjectParameter("pcIDCLiente", typeof(string));
    
            var pcIDPrestamoParameter = pcIDPrestamo != null ?
                new ObjectParameter("pcIDPrestamo", pcIDPrestamo) :
                new ObjectParameter("pcIDPrestamo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_SRCEstadoDeCuenta", pcIDCLienteParameter, pcIDPrestamoParameter);
        }
    
        public virtual ObjectResult<sp_GeoBarrios_Result> sp_GeoBarrios(Nullable<short> piPais, Nullable<short> piDepartamento, Nullable<short> piMunicipio, Nullable<short> piPoblado, Nullable<short> piBarrio)
        {
            var piPaisParameter = piPais.HasValue ?
                new ObjectParameter("piPais", piPais) :
                new ObjectParameter("piPais", typeof(short));
    
            var piDepartamentoParameter = piDepartamento.HasValue ?
                new ObjectParameter("piDepartamento", piDepartamento) :
                new ObjectParameter("piDepartamento", typeof(short));
    
            var piMunicipioParameter = piMunicipio.HasValue ?
                new ObjectParameter("piMunicipio", piMunicipio) :
                new ObjectParameter("piMunicipio", typeof(short));
    
            var piPobladoParameter = piPoblado.HasValue ?
                new ObjectParameter("piPoblado", piPoblado) :
                new ObjectParameter("piPoblado", typeof(short));
    
            var piBarrioParameter = piBarrio.HasValue ?
                new ObjectParameter("piBarrio", piBarrio) :
                new ObjectParameter("piBarrio", typeof(short));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GeoBarrios_Result>("sp_GeoBarrios", piPaisParameter, piDepartamentoParameter, piMunicipioParameter, piPobladoParameter, piBarrioParameter);
        }
    
        public virtual ObjectResult<sp_GeoDepartamento_Result> sp_GeoDepartamento(Nullable<short> piPais, Nullable<short> piDepartamento)
        {
            var piPaisParameter = piPais.HasValue ?
                new ObjectParameter("piPais", piPais) :
                new ObjectParameter("piPais", typeof(short));
    
            var piDepartamentoParameter = piDepartamento.HasValue ?
                new ObjectParameter("piDepartamento", piDepartamento) :
                new ObjectParameter("piDepartamento", typeof(short));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GeoDepartamento_Result>("sp_GeoDepartamento", piPaisParameter, piDepartamentoParameter);
        }
    
        public virtual ObjectResult<sp_GeoMunicipio_Result> sp_GeoMunicipio(Nullable<short> piPais, Nullable<short> piDepartamento, Nullable<short> piMunicipio)
        {
            var piPaisParameter = piPais.HasValue ?
                new ObjectParameter("piPais", piPais) :
                new ObjectParameter("piPais", typeof(short));
    
            var piDepartamentoParameter = piDepartamento.HasValue ?
                new ObjectParameter("piDepartamento", piDepartamento) :
                new ObjectParameter("piDepartamento", typeof(short));
    
            var piMunicipioParameter = piMunicipio.HasValue ?
                new ObjectParameter("piMunicipio", piMunicipio) :
                new ObjectParameter("piMunicipio", typeof(short));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GeoMunicipio_Result>("sp_GeoMunicipio", piPaisParameter, piDepartamentoParameter, piMunicipioParameter);
        }
    
        public virtual ObjectResult<sp_GeoPais_Result> sp_GeoPais(Nullable<short> piPais)
        {
            var piPaisParameter = piPais.HasValue ?
                new ObjectParameter("piPais", piPais) :
                new ObjectParameter("piPais", typeof(short));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GeoPais_Result>("sp_GeoPais", piPaisParameter);
        }
    
        public virtual ObjectResult<sp_GeoPoblado_Result> sp_GeoPoblado(Nullable<int> piPais, Nullable<int> piDepartamento, Nullable<int> piMunicipio, Nullable<int> piPoblado)
        {
            var piPaisParameter = piPais.HasValue ?
                new ObjectParameter("piPais", piPais) :
                new ObjectParameter("piPais", typeof(int));
    
            var piDepartamentoParameter = piDepartamento.HasValue ?
                new ObjectParameter("piDepartamento", piDepartamento) :
                new ObjectParameter("piDepartamento", typeof(int));
    
            var piMunicipioParameter = piMunicipio.HasValue ?
                new ObjectParameter("piMunicipio", piMunicipio) :
                new ObjectParameter("piMunicipio", typeof(int));
    
            var piPobladoParameter = piPoblado.HasValue ?
                new ObjectParameter("piPoblado", piPoblado) :
                new ObjectParameter("piPoblado", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GeoPoblado_Result>("sp_GeoPoblado", piPaisParameter, piDepartamentoParameter, piMunicipioParameter, piPobladoParameter);
        }
    
        public virtual ObjectResult<sp_OperacionesCaja_ConsultarCliente_NovaNet_Result> sp_OperacionesCaja_ConsultarCliente_NovaNet(Nullable<int> piIDSesion, Nullable<short> piIDApp, Nullable<int> piIDUsuario, string pcIdentidad)
        {
            var piIDSesionParameter = piIDSesion.HasValue ?
                new ObjectParameter("piIDSesion", piIDSesion) :
                new ObjectParameter("piIDSesion", typeof(int));
    
            var piIDAppParameter = piIDApp.HasValue ?
                new ObjectParameter("piIDApp", piIDApp) :
                new ObjectParameter("piIDApp", typeof(short));
    
            var piIDUsuarioParameter = piIDUsuario.HasValue ?
                new ObjectParameter("piIDUsuario", piIDUsuario) :
                new ObjectParameter("piIDUsuario", typeof(int));
    
            var pcIdentidadParameter = pcIdentidad != null ?
                new ObjectParameter("pcIdentidad", pcIdentidad) :
                new ObjectParameter("pcIdentidad", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_OperacionesCaja_ConsultarCliente_NovaNet_Result>("sp_OperacionesCaja_ConsultarCliente_NovaNet", piIDSesionParameter, piIDAppParameter, piIDUsuarioParameter, pcIdentidadParameter);
        }
    
        public virtual int sp_OperacionesCaja_ConsultarCliente_NovaNet_PorPrestamo(Nullable<int> piIDSesion, Nullable<short> piIDApp, Nullable<int> piIDUsuario, string pcIdentidad, string pcIDPrestamo)
        {
            var piIDSesionParameter = piIDSesion.HasValue ?
                new ObjectParameter("piIDSesion", piIDSesion) :
                new ObjectParameter("piIDSesion", typeof(int));
    
            var piIDAppParameter = piIDApp.HasValue ?
                new ObjectParameter("piIDApp", piIDApp) :
                new ObjectParameter("piIDApp", typeof(short));
    
            var piIDUsuarioParameter = piIDUsuario.HasValue ?
                new ObjectParameter("piIDUsuario", piIDUsuario) :
                new ObjectParameter("piIDUsuario", typeof(int));
    
            var pcIdentidadParameter = pcIdentidad != null ?
                new ObjectParameter("pcIdentidad", pcIdentidad) :
                new ObjectParameter("pcIdentidad", typeof(string));
    
            var pcIDPrestamoParameter = pcIDPrestamo != null ?
                new ObjectParameter("pcIDPrestamo", pcIDPrestamo) :
                new ObjectParameter("pcIDPrestamo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_OperacionesCaja_ConsultarCliente_NovaNet_PorPrestamo", piIDSesionParameter, piIDAppParameter, piIDUsuarioParameter, pcIdentidadParameter, pcIDPrestamoParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_CREDGarantias_ActualizarSerieDeProducto(Nullable<int> piIDSolicitud, string pcIDPrestamo, string pcSerieProducto)
        {
            var piIDSolicitudParameter = piIDSolicitud.HasValue ?
                new ObjectParameter("piIDSolicitud", piIDSolicitud) :
                new ObjectParameter("piIDSolicitud", typeof(int));
    
            var pcIDPrestamoParameter = pcIDPrestamo != null ?
                new ObjectParameter("pcIDPrestamo", pcIDPrestamo) :
                new ObjectParameter("pcIDPrestamo", typeof(string));
    
            var pcSerieProductoParameter = pcSerieProducto != null ?
                new ObjectParameter("pcSerieProducto", pcSerieProducto) :
                new ObjectParameter("pcSerieProducto", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_CREDGarantias_ActualizarSerieDeProducto", piIDSolicitudParameter, pcIDPrestamoParameter, pcSerieProductoParameter);
        }
    }
}
